/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const _kSleepFontFam = 'sleepIcon';
  static const String? _kFontPkg = null;

  static const IconData scale =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData fi_rr_ruler =
      IconData(0xe801, fontFamily: _kFontFam);
  static const IconData fi_rr_calendar =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData fi_rr_clock_1 =
      IconData(0xe803, fontFamily: _kFontFam);
  static const IconData fi_rr_upload =
      IconData(0xe804, fontFamily: _kFontFam);

  static const IconData sleep_start =
      IconData(0xe800, fontFamily: _kSleepFontFam);
  static const IconData sleep_end =
      IconData(0xe801, fontFamily: _kSleepFontFam);
}
