import '../../domain/entities/patient.dart';
import '../../domain/entities/vitals.dart';
import '../../domain/value_objects/risk_tier.dart';
import '../../domain/value_objects/status.dart';

class MockPatientDataSource {
  List<Patient> getMockPatients() {
    return [
      Patient(
        id: 'P001',
        name: 'Sarah Johnson',
        age: 67,
        sex: 'Female',
        twinId: 'DT-2024-001',
        riskTier: RiskTier.high,
        lastEvaluation: 'Jan 6, 2026',
        nextAction: 'Review AI recommendation',
        status: Status.needsReview,
        cohort: ['Cardiac', 'Diabetes'],
        conditions: ['Atrial Fibrillation', 'Type 2 Diabetes', 'Hypertension'],
        medications: ['Warfarin 5mg', 'Metformin 1000mg', 'Lisinopril 10mg'],
        vitals: const Vitals(
          bloodPressure: '142/88',
          heartRate: '78',
          temperature: '98.6°F',
        ),
      ),
      Patient(
        id: 'P002',
        name: 'Michael Chen',
        age: 54,
        sex: 'Male',
        twinId: 'DT-2024-002',
        riskTier: RiskTier.medium,
        lastEvaluation: 'Jan 5, 2026',
        nextAction: 'Scheduled follow-up Jan 20',
        status: Status.monitoring,
        cohort: ['Cardiac'],
        conditions: ['Coronary Artery Disease', 'Hyperlipidemia'],
        medications: ['Atorvastatin 40mg', 'Aspirin 81mg', 'Metoprolol 50mg'],
        vitals: const Vitals(
          bloodPressure: '128/82',
          heartRate: '72',
          temperature: '98.4°F',
        ),
      ),
      Patient(
        id: 'P003',
        name: 'Emily Rodriguez',
        age: 71,
        sex: 'Female',
        twinId: 'DT-2024-003',
        riskTier: RiskTier.low,
        lastEvaluation: 'Jan 7, 2026',
        nextAction: 'Continue monitoring',
        status: Status.actionTaken,
        cohort: ['Cardiac'],
        conditions: ['Post-CABG', 'Hypertension'],
        medications: ['Carvedilol 25mg', 'Clopidogrel 75mg'],
        vitals: const Vitals(
          bloodPressure: '118/76',
          heartRate: '68',
          temperature: '98.2°F',
        ),
      ),
      Patient(
        id: 'P004',
        name: 'Robert Kim',
        age: 62,
        sex: 'Male',
        twinId: 'DT-2024-004',
        riskTier: RiskTier.high,
        lastEvaluation: 'Jan 4, 2026',
        nextAction: 'Review AI recommendation',
        status: Status.needsReview,
        cohort: ['Cardiac', 'Renal'],
        conditions: ['Heart Failure', 'CKD Stage 3', 'Diabetes'],
        medications: ['Entresto 49/51mg', 'Furosemide 40mg', 'Insulin Glargine'],
      ),
      Patient(
        id: 'P005',
        name: 'Linda Martinez',
        age: 59,
        sex: 'Female',
        twinId: 'DT-2024-005',
        riskTier: RiskTier.medium,
        lastEvaluation: 'Jan 8, 2026',
        nextAction: 'Labs ordered, pending results',
        status: Status.monitoring,
        cohort: ['Diabetes'],
        conditions: ['Type 2 Diabetes', 'Obesity', 'Sleep Apnea'],
        medications: ['Ozempic 1mg weekly', 'Metformin 1000mg'],
      ),
      Patient(
        id: 'P006',
        name: 'James Wilson',
        age: 76,
        sex: 'Male',
        twinId: 'DT-2024-006',
        riskTier: RiskTier.low,
        lastEvaluation: 'Jan 3, 2026',
        nextAction: 'Next visit Feb 15',
        status: Status.actionTaken,
        cohort: ['Cardiac'],
        conditions: ['Stable Angina', 'Hypertension'],
        medications: ['Amlodipine 10mg', 'Nitroglycerin PRN'],
      ),
    ];
  }
}
