-- Generated from FluxFHIR BigQuery ResourceSchema definitions
-- Source: git@github.com:Marchhealth/FluxFHIR.git
-- Target: PostgreSQL (AWS RDS compatible)

create schema if not exists fluxfhir_dev;
set search_path to fluxfhir_dev, public;

-- Source table CarePlan -> fluxfhir_dev.care_plan
create table if not exists fluxfhir_dev.care_plan (
  id text,
  resource_type text,
  meta_version_id text,
  meta_last_updated timestamptz,
  meta_profile_0 text,
  text_status text,
  text_div text,
  identifier_0_system text,
  identifier_0_value text,
  instantiates_canonical_0 text,
  status text,
  intent text,
  category_0_coding_0_system text,
  category_0_coding_0_code text,
  category_0_coding_0_display text,
  title text,
  description text,
  subject_reference text,
  subject_display text,
  encounter_reference text,
  period_start timestamptz,
  period_end timestamptz,
  created timestamptz,
  author_reference text,
  author_display text,
  contributor_0_reference text,
  contributor_0_display text,
  contributor_1_reference text,
  contributor_1_display text,
  care_team_0_reference text,
  addresses_0_reference text,
  addresses_0_display text,
  supporting_info_0_reference text,
  supporting_info_0_display text,
  goal_0_reference text,
  goal_0_display text,
  goal_1_reference text,
  goal_1_display text,
  activity_0_kind text,
  activity_0_status text,
  activity_0_status_reason_coding_0_system text,
  activity_0_status_reason_coding_0_code text,
  activity_0_status_reason_coding_0_display text,
  activity_0_reference_reference text,
  activity_0_reference_display text,
  activity_0_detail_kind text,
  activity_0_detail_status text,
  activity_0_detail_do_not_perform boolean,
  activity_0_detail_scheduled_timing_repeat_period_unit text,
  activity_0_detail_location_reference text,
  activity_0_detail_location_display text,
  activity_0_detail_performer_0_reference text,
  activity_0_detail_description text,
  activity_1_kind text,
  activity_1_status text,
  activity_1_reference_reference text,
  activity_1_reference_display text,
  activity_1_detail_kind text,
  activity_1_detail_status text,
  activity_1_detail_do_not_perform boolean,
  activity_1_detail_scheduled_timing_repeat_period_unit text,
  activity_1_detail_description text,
  activity_2_kind text,
  activity_2_status text,
  activity_2_reference_reference text,
  activity_2_reference_display text,
  activity_2_detail_kind text,
  activity_2_detail_status text,
  activity_2_detail_do_not_perform boolean,
  activity_2_detail_scheduled_timing_repeat_period_unit text,
  activity_2_detail_description text,
  activity_3_kind text,
  activity_3_status text,
  activity_3_reference_reference text,
  activity_3_reference_display text,
  activity_3_detail_kind text,
  activity_3_detail_status text,
  activity_3_detail_do_not_perform boolean,
  activity_3_detail_description text,
  activity_4_kind text,
  activity_4_status text,
  activity_4_reference_reference text,
  activity_4_reference_display text,
  activity_4_detail_kind text,
  activity_4_detail_status text,
  activity_4_detail_do_not_perform boolean,
  activity_4_detail_scheduled_timing_repeat_period_unit text,
  activity_4_detail_description text,
  note_0_author_reference_reference text,
  note_0_time timestamptz,
  note_0_text text,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_care_plan_resource_type on fluxfhir_dev.care_plan (resource_type);
create index if not exists idx_care_plan_subject_reference on fluxfhir_dev.care_plan (subject_reference);
create index if not exists idx_care_plan_encounter_reference on fluxfhir_dev.care_plan (encounter_reference);
create index if not exists idx_care_plan_created_at on fluxfhir_dev.care_plan (created_at);
create index if not exists idx_care_plan_updated_at on fluxfhir_dev.care_plan (updated_at);

-- Source table Condition -> fluxfhir_dev.condition
create table if not exists fluxfhir_dev.condition (
  id text,
  resource_type text,
  meta_version_id text,
  meta_last_updated timestamptz,
  meta_profile_0 text,
  clinical_status_coding_0_system text,
  clinical_status_coding_0_code text,
  clinical_status_coding_0_display text,
  verification_status_coding_0_system text,
  verification_status_coding_0_code text,
  verification_status_coding_0_display text,
  category_0_coding_0_system text,
  category_0_coding_0_code text,
  category_0_coding_0_display text,
  code_coding_0_system text,
  code_coding_0_code text,
  code_coding_0_display text,
  code_coding_1_system text,
  code_coding_1_code text,
  code_coding_1_display text,
  code_text text,
  subject_reference text,
  subject_display text,
  encounter_reference text,
  onset_date_time date,
  recorded_date timestamptz,
  recorder_reference text,
  recorder_display text,
  stage_0_summary_coding_0_system text,
  stage_0_summary_coding_0_code text,
  stage_0_summary_coding_0_display text,
  stage_0_type_coding_0_system text,
  stage_0_type_coding_0_code text,
  stage_0_type_coding_0_display text,
  evidence_0_concept_coding_0_system text,
  evidence_0_concept_coding_0_code text,
  evidence_0_concept_coding_0_display text,
  evidence_1_concept_coding_0_system text,
  evidence_1_concept_coding_0_code text,
  evidence_1_concept_coding_0_display text,
  evidence_0_reference_reference text,
  evidence_0_reference_display text,
  evidence_1_reference_reference text,
  evidence_1_reference_display text,
  evidence_2_reference_reference text,
  evidence_2_reference_display text,
  evidence_2_concept_coding_0_system text,
  evidence_2_concept_coding_0_code text,
  evidence_2_concept_coding_0_display text,
  body_site_0_coding_0_system text,
  body_site_0_coding_0_code text,
  body_site_0_coding_0_display text,
  note_0_author_reference_reference text,
  note_0_time timestamptz,
  note_0_text text,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_condition_resource_type on fluxfhir_dev.condition (resource_type);
create index if not exists idx_condition_subject_reference on fluxfhir_dev.condition (subject_reference);
create index if not exists idx_condition_encounter_reference on fluxfhir_dev.condition (encounter_reference);
create index if not exists idx_condition_created_at on fluxfhir_dev.condition (created_at);
create index if not exists idx_condition_updated_at on fluxfhir_dev.condition (updated_at);

-- Source table Encounter -> fluxfhir_dev.encounter
create table if not exists fluxfhir_dev.encounter (
  id text,
  resource_type text,
  meta_version_id text,
  meta_last_updated timestamptz,
  meta_profile_0 text,
  text_status text,
  text_div text,
  identifier_0_system text,
  identifier_0_value text,
  status text,
  class_0_system text,
  class_0_code text,
  class_0_display text,
  type_0_coding_0_system text,
  type_0_coding_0_code text,
  type_0_coding_0_display text,
  type_0_text text,
  reason_0_use text,
  reason_0_value_coding_0_system text,
  reason_0_value_coding_0_code text,
  reason_0_value_coding_0_display text,
  subject_reference text,
  subject_display text,
  participant_0_type_0_coding_0_system text,
  participant_0_type_0_coding_0_code text,
  participant_0_type_0_coding_0_display text,
  participant_0_actor_reference text,
  participant_0_actor_display text,
  participant_1_type_0_coding_0_system text,
  participant_1_type_0_coding_0_code text,
  participant_1_type_0_coding_0_display text,
  participant_1_actor_reference text,
  participant_1_actor_display text,
  period_start timestamptz,
  period_end timestamptz,
  length_unit text,
  length_system text,
  length_code text,
  priority_coding_0_system text,
  priority_coding_0_code text,
  priority_coding_0_display text,
  location_0_location_reference text,
  location_0_location_display text,
  location_0_status text,
  admission_admit_source_coding_0_system text,
  admission_admit_source_coding_0_code text,
  admission_admit_source_coding_0_display text,
  admission_discharge_disposition_coding_0_system text,
  admission_discharge_disposition_coding_0_code text,
  admission_discharge_disposition_coding_0_display text,
  admission_re_admission_coding_0_system text,
  admission_re_admission_coding_0_code text,
  admission_re_admission_coding_0_display text,
  service_provider_reference text,
  service_provider_display text,
  part_of_reference text,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_encounter_resource_type on fluxfhir_dev.encounter (resource_type);
create index if not exists idx_encounter_subject_reference on fluxfhir_dev.encounter (subject_reference);
create index if not exists idx_encounter_created_at on fluxfhir_dev.encounter (created_at);
create index if not exists idx_encounter_updated_at on fluxfhir_dev.encounter (updated_at);

-- Source table FallbackJson -> fluxfhir_dev.fallback_json
create table if not exists fluxfhir_dev.fallback_json (
  id text,
  resource_type text,
  payload jsonb,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_fallback_json_resource_type on fluxfhir_dev.fallback_json (resource_type);
create index if not exists idx_fallback_json_created_at on fluxfhir_dev.fallback_json (created_at);
create index if not exists idx_fallback_json_updated_at on fluxfhir_dev.fallback_json (updated_at);

-- Source table FamilyMemberHistory -> fluxfhir_dev.family_member_history
create table if not exists fluxfhir_dev.family_member_history (
  id text,
  resource_type text,
  meta_version_id text,
  meta_last_updated timestamptz,
  meta_source text,
  meta_profile_0 text,
  meta_security_0_system text,
  meta_security_0_code text,
  meta_security_0_display text,
  meta_tag_0_system text,
  meta_tag_0_code text,
  meta_tag_0_display text,
  text_status text,
  text_div text,
  identifier_0_use text,
  identifier_0_type_coding_0_system text,
  identifier_0_type_coding_0_code text,
  identifier_0_type_coding_0_display text,
  identifier_0_system text,
  identifier_0_value text,
  identifier_0_period_start timestamptz,
  identifier_0_period_end timestamptz,
  identifier_0_assigner_display text,
  instantiates_canonical_0 text,
  instantiates_uri_0 text,
  status text,
  data_absent_reason_coding_0_system text,
  data_absent_reason_coding_0_code text,
  data_absent_reason_coding_0_display text,
  data_absent_reason_text text,
  patient_reference text,
  patient_display text,
  date timestamptz,
  name text,
  relationship_coding_0_system text,
  relationship_coding_0_code text,
  relationship_coding_0_display text,
  relationship_text text,
  sex_coding_0_system text,
  sex_coding_0_code text,
  sex_coding_0_display text,
  sex_text text,
  born_value_date_time date,
  born_value_period_start date,
  born_value_period_end date,
  born_value_string text,
  age_value_age_unit text,
  age_value_age_system text,
  age_value_age_code text,
  age_value_range_low_unit text,
  age_value_range_high_unit text,
  age_value_string text,
  estimated_age boolean,
  deceased_value_boolean boolean,
  deceased_value_date_time date,
  deceased_value_age_unit text,
  deceased_value_range_low_unit text,
  deceased_value_range_high_unit text,
  deceased_value_string text,
  reason_code_0_coding_0_system text,
  reason_code_0_coding_0_code text,
  reason_code_0_coding_0_display text,
  reason_code_0_text text,
  reason_reference_0_reference text,
  reason_reference_0_display text,
  participant_0_type_coding_0_system text,
  participant_0_type_coding_0_code text,
  participant_0_type_coding_0_display text,
  participant_0_actor_reference text,
  participant_0_actor_display text,
  encounter_reference text,
  encounter_display text,
  condition_0_code_coding_0_system text,
  condition_0_code_coding_0_code text,
  condition_0_code_coding_0_display text,
  condition_0_code_text text,
  condition_0_outcome_coding_0_system text,
  condition_0_outcome_coding_0_code text,
  condition_0_outcome_coding_0_display text,
  condition_0_outcome_text text,
  condition_0_contributed_to_death boolean,
  condition_0_onset_age_unit text,
  condition_0_onset_age_system text,
  condition_0_onset_age_code text,
  condition_0_onset_string text,
  condition_0_note_0_text text,
  note_0_text text,
  procedure_0_code_coding_0_system text,
  procedure_0_code_coding_0_code text,
  procedure_0_code_coding_0_display text,
  procedure_0_code_text text,
  procedure_0_outcome_coding_0_system text,
  procedure_0_outcome_coding_0_code text,
  procedure_0_outcome_coding_0_display text,
  procedure_0_outcome_text text,
  procedure_0_performed_date_time timestamptz,
  procedure_0_performed_period_start timestamptz,
  procedure_0_performed_period_end timestamptz,
  procedure_0_note_0_text text,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_family_member_history_resource_type on fluxfhir_dev.family_member_history (resource_type);
create index if not exists idx_family_member_history_patient_reference on fluxfhir_dev.family_member_history (patient_reference);
create index if not exists idx_family_member_history_encounter_reference on fluxfhir_dev.family_member_history (encounter_reference);
create index if not exists idx_family_member_history_created_at on fluxfhir_dev.family_member_history (created_at);
create index if not exists idx_family_member_history_updated_at on fluxfhir_dev.family_member_history (updated_at);

-- Source table MedicationAdministration -> fluxfhir_dev.medication_administration
create table if not exists fluxfhir_dev.medication_administration (
  id text,
  resource_type text,
  meta_version_id text,
  meta_last_updated timestamptz,
  meta_profile_0 text,
  status text,
  status_reason_0_coding_0_system text,
  status_reason_0_coding_0_code text,
  status_reason_0_coding_0_display text,
  status_reason_0_text text,
  category_0_coding_0_system text,
  category_0_coding_0_code text,
  category_0_coding_0_display text,
  category_0_text text,
  medication_concept_coding_0_system text,
  medication_concept_coding_0_code text,
  medication_concept_coding_0_display text,
  medication_concept_text text,
  medication_reference_reference text,
  medication_reference_display text,
  subject_reference text,
  subject_display text,
  encounter_reference text,
  encounter_display text,
  occurence_date_time timestamptz,
  occurence_period_start timestamptz,
  occurence_period_end timestamptz,
  occurence_timing_event_0 timestamptz,
  occurence_string text,
  request_reference text,
  request_display text,
  reason_0_concept_coding_0_system text,
  reason_0_concept_coding_0_code text,
  reason_0_concept_coding_0_display text,
  reason_0_concept_text text,
  reason_0_reference_reference text,
  reason_0_reference_display text,
  supporting_information_0_reference text,
  supporting_information_0_display text,
  performer_0_function_coding_0_system text,
  performer_0_function_coding_0_code text,
  performer_0_function_coding_0_display text,
  performer_0_actor_reference text,
  performer_0_actor_display text,
  performer_0_on_behalf_of_reference text,
  performer_0_on_behalf_of_display text,
  dosage_site_coding_0_system text,
  dosage_site_coding_0_code text,
  dosage_site_coding_0_display text,
  dosage_site_text text,
  dosage_route_coding_0_system text,
  dosage_route_coding_0_code text,
  dosage_route_coding_0_display text,
  dosage_route_text text,
  dosage_method_coding_0_system text,
  dosage_method_coding_0_code text,
  dosage_method_coding_0_display text,
  dosage_method_text text,
  dosage_dose_unit text,
  dosage_dose_system text,
  dosage_dose_code text,
  dosage_rate_ratio_numerator_comparator text,
  dosage_rate_ratio_numerator_unit text,
  dosage_rate_ratio_numerator_system text,
  dosage_rate_ratio_numerator_code text,
  dosage_rate_ratio_denominator_comparator text,
  dosage_rate_ratio_denominator_unit text,
  dosage_rate_ratio_denominator_system text,
  dosage_rate_ratio_denominator_code text,
  dosage_rate_quantity_unit text,
  dosage_rate_quantity_system text,
  dosage_rate_quantity_code text,
  device_0_concept_coding_0_system text,
  device_0_concept_coding_0_code text,
  device_0_concept_coding_0_display text,
  device_0_concept_text text,
  device_0_reference_reference text,
  device_0_reference_display text,
  note_0_author_reference_reference text,
  note_0_author_reference_display text,
  note_0_time timestamptz,
  note_0_text text,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_medication_administration_resource_type on fluxfhir_dev.medication_administration (resource_type);
create index if not exists idx_medication_administration_subject_reference on fluxfhir_dev.medication_administration (subject_reference);
create index if not exists idx_medication_administration_encounter_reference on fluxfhir_dev.medication_administration (encounter_reference);
create index if not exists idx_medication_administration_created_at on fluxfhir_dev.medication_administration (created_at);
create index if not exists idx_medication_administration_updated_at on fluxfhir_dev.medication_administration (updated_at);

-- Source table MedicationRequest -> fluxfhir_dev.medication_request
create table if not exists fluxfhir_dev.medication_request (
  id text,
  resource_type text,
  meta_profile_0 text,
  status text,
  status_changed timestamptz,
  status_reason_coding_0_system text,
  status_reason_coding_0_code text,
  status_reason_coding_0_display text,
  status_reason_text text,
  intent text,
  category_0_coding_0_system text,
  category_0_coding_0_code text,
  category_0_coding_0_display text,
  category_0_text text,
  priority text,
  do_not_perform boolean,
  medication_concept_coding_0_system text,
  medication_concept_coding_0_code text,
  medication_concept_coding_0_display text,
  medication_concept_text text,
  subject_reference text,
  subject_display text,
  encounter_reference text,
  information_source_0_reference text,
  information_source_0_display text,
  authored_on timestamptz,
  requester_reference text,
  requester_display text,
  reason_0_concept_coding_0_system text,
  reason_0_concept_coding_0_code text,
  reason_0_concept_coding_0_display text,
  reason_0_concept_text text,
  insurance_0_reference text,
  insurance_0_display text,
  group_identifier_system text,
  group_identifier_value text,
  based_on_0_reference text,
  note_0_author_reference_reference text,
  note_0_author_reference_display text,
  note_0_time timestamptz,
  note_0_text text,
  dosage_instruction_0_text text,
  dosage_instruction_0_patient_instruction text,
  dosage_instruction_0_timing_repeat_period_unit text,
  dosage_instruction_0_timing_repeat_when_0 text,
  dosage_instruction_0_route_coding_0_system text,
  dosage_instruction_0_route_coding_0_code text,
  dosage_instruction_0_route_coding_0_display text,
  dosage_instruction_0_route_text text,
  dosage_instruction_0_dose_and_rate_0_dose_quantity_unit text,
  dosage_instruction_0_dose_and_rate_0_dose_quantity_code text,
  dosage_instruction_0_max_dose_per_administration_value numeric,
  dosage_instruction_0_max_dose_per_administration_unit text,
  dosage_instruction_0_max_dose_per_administration_system text,
  dosage_instruction_0_max_dose_per_administration_code text,
  dispense_request_initial_fill_quantity_value numeric,
  dispense_request_initial_fill_quantity_unit text,
  dispense_request_initial_fill_quantity_system text,
  dispense_request_initial_fill_quantity_code text,
  dispense_request_initial_fill_duration_value numeric,
  dispense_request_initial_fill_duration_unit text,
  dispense_request_initial_fill_duration_system text,
  dispense_request_initial_fill_duration_code text,
  dispense_request_quantity_value numeric,
  dispense_request_quantity_unit text,
  dispense_request_quantity_system text,
  dispense_request_quantity_code text,
  dispense_request_expected_supply_duration_value numeric,
  dispense_request_expected_supply_duration_unit text,
  dispense_request_expected_supply_duration_system text,
  dispense_request_expected_supply_duration_code text,
  dispense_request_dispenser_reference text,
  dispense_request_dispenser_display text,
  dispense_request_dispenser_instruction_0_text text,
  dispense_request_dispenser_instruction_0_time timestamptz,
  substitution_allowed_boolean boolean,
  substitution_reason_coding_0_system text,
  substitution_reason_coding_0_code text,
  substitution_reason_coding_0_display text,
  substitution_reason_text text,
  event_history_0_reference text,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_medication_request_resource_type on fluxfhir_dev.medication_request (resource_type);
create index if not exists idx_medication_request_subject_reference on fluxfhir_dev.medication_request (subject_reference);
create index if not exists idx_medication_request_encounter_reference on fluxfhir_dev.medication_request (encounter_reference);
create index if not exists idx_medication_request_created_at on fluxfhir_dev.medication_request (created_at);
create index if not exists idx_medication_request_updated_at on fluxfhir_dev.medication_request (updated_at);

-- Source table Medication -> fluxfhir_dev.medication
create table if not exists fluxfhir_dev.medication (
  id text,
  resource_type text,
  meta_version_id text,
  meta_last_updated timestamptz,
  meta_source text,
  meta_profile_0 text,
  meta_security_0_system text,
  meta_security_0_code text,
  meta_security_0_display text,
  meta_tag_0_system text,
  meta_tag_0_code text,
  meta_tag_0_display text,
  text_status text,
  text_div text,
  identifier_0_use text,
  identifier_0_type_coding_0_system text,
  identifier_0_type_coding_0_code text,
  identifier_0_type_coding_0_display text,
  identifier_0_system text,
  identifier_0_value text,
  identifier_0_period_start timestamptz,
  identifier_0_period_end timestamptz,
  identifier_0_assigner_display text,
  identifier_1_use text,
  identifier_1_type_coding_0_system text,
  identifier_1_type_coding_0_code text,
  identifier_1_type_coding_0_display text,
  identifier_1_system text,
  identifier_1_value text,
  identifier_1_period_start timestamptz,
  identifier_1_period_end timestamptz,
  identifier_1_assigner_display text,
  status text,
  code_coding_0_system text,
  code_coding_0_code text,
  code_coding_0_display text,
  code_coding_1_system text,
  code_coding_1_code text,
  code_coding_1_display text,
  code_text text,
  dose_form_coding_0_system text,
  dose_form_coding_0_code text,
  dose_form_coding_0_display text,
  dose_form_text text,
  amount_numerator_comparator text,
  amount_numerator_unit text,
  amount_numerator_system text,
  amount_numerator_code text,
  amount_denominator_comparator text,
  amount_denominator_unit text,
  amount_denominator_system text,
  amount_denominator_code text,
  ingredient_0_item_concept_coding_0_system text,
  ingredient_0_item_concept_coding_0_code text,
  ingredient_0_item_concept_coding_0_display text,
  ingredient_0_item_concept_text text,
  ingredient_0_item_reference text,
  ingredient_0_is_active boolean,
  ingredient_0_strength_numerator_comparator text,
  ingredient_0_strength_numerator_unit text,
  ingredient_0_strength_numerator_system text,
  ingredient_0_strength_numerator_code text,
  ingredient_0_strength_denominator_comparator text,
  ingredient_0_strength_denominator_unit text,
  ingredient_0_strength_denominator_system text,
  ingredient_0_strength_denominator_code text,
  batch_lot_number text,
  batch_expiration_date date,
  manufacturer_reference text,
  manufacturer_display text,
  marketing_authorization_holder_reference text,
  marketing_authorization_holder_display text,
  pure_substance_concept_coding_0_system text,
  pure_substance_concept_coding_0_code text,
  pure_substance_concept_coding_0_display text,
  pure_substance_reference text,
  note_0_text text,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_medication_resource_type on fluxfhir_dev.medication (resource_type);
create index if not exists idx_medication_created_at on fluxfhir_dev.medication (created_at);
create index if not exists idx_medication_updated_at on fluxfhir_dev.medication (updated_at);

-- Source table Observation -> fluxfhir_dev.observation
create table if not exists fluxfhir_dev.observation (
  id text,
  resource_type text,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  status text,
  text_status text,
  text_div text,
  meta_version_id text,
  meta_last_updated timestamptz,
  meta_profile_0 text,
  effective_date_time timestamptz,
  effective_instant timestamptz,
  effective_period_start timestamptz,
  effective_period_end timestamptz,
  issued timestamptz,
  effective_timing_repeat_period_unit text,
  subject_reference text,
  subject_display text,
  subject_type text,
  encounter_reference text,
  encounter_display text,
  encounter_type text,
  performer_0_reference text,
  performer_0_display text,
  performer_0_type text,
  performer_1_reference text,
  performer_1_display text,
  performer_1_type text,
  device_reference text,
  device_display text,
  device_type text,
  specimen_reference text,
  specimen_display text,
  specimen_type text,
  based_on_0_reference text,
  based_on_0_display text,
  based_on_0_type text,
  part_of_0_reference text,
  part_of_0_display text,
  part_of_0_type text,
  has_member_0_reference text,
  has_member_0_display text,
  has_member_0_type text,
  has_member_1_reference text,
  has_member_1_display text,
  has_member_1_type text,
  has_member_2_reference text,
  has_member_2_display text,
  has_member_2_type text,
  focus_0_reference text,
  focus_0_display text,
  focus_0_type text,
  body_site_coding_0_system text,
  body_site_coding_0_code text,
  body_site_coding_0_display text,
  body_site_text text,
  body_structure_reference text,
  body_structure_display text,
  body_structure_type text,
  triggered_by_0_observation_reference text,
  triggered_by_0_observation_display text,
  triggered_by_0_observation_type text,
  triggered_by_0_reason text,
  triggered_by_0_type text,
  category_0_coding_0_system text,
  category_0_coding_0_code text,
  category_0_coding_0_display text,
  category_0_text text,
  code_coding_0_system text,
  code_coding_0_code text,
  code_coding_0_display text,
  code_coding_1_system text,
  code_coding_1_code text,
  code_coding_1_display text,
  code_text text,
  instantiates_canonical_0 text,
  instantiates_reference_0_reference text,
  instantiates_reference_0_display text,
  instantiates_reference_0_type text,
  method_coding_0_system text,
  method_coding_0_code text,
  method_coding_0_display text,
  method_text text,
  value_quantity_unit text,
  value_quantity_system text,
  value_quantity_code text,
  value_quantity_comparator text,
  value_codeable_concept_coding_0_system text,
  value_codeable_concept_coding_0_code text,
  value_codeable_concept_coding_0_display text,
  value_codeable_concept_coding_1_system text,
  value_codeable_concept_coding_1_code text,
  value_codeable_concept_coding_1_display text,
  value_codeable_concept_text text,
  value_string text,
  value_boolean boolean,
  value_time time,
  value_range_low_unit text,
  value_range_high_unit text,
  value_ratio_numerator_unit text,
  value_ratio_denominator_unit text,
  value_period_start timestamptz,
  value_period_end timestamptz,
  value_attachment_content_type text,
  value_attachment_creation timestamptz,
  value_attachment_url text,
  value_attachment_title text,
  value_sampled_data_data text,
  component_0_code_coding_0_system text,
  component_0_code_coding_0_code text,
  component_0_code_coding_0_display text,
  component_0_value_quantity_unit text,
  component_0_value_quantity_system text,
  component_0_value_quantity_code text,
  component_0_interpretation_0_coding_0_system text,
  component_0_interpretation_0_coding_0_code text,
  component_0_interpretation_0_coding_0_display text,
  component_0_reference_range_0_low_unit text,
  component_0_reference_range_0_high_unit text,
  component_0_data_absent_reason_coding_0_system text,
  component_0_data_absent_reason_coding_0_code text,
  component_0_data_absent_reason_coding_0_display text,
  component_1_code_coding_0_system text,
  component_1_code_coding_0_code text,
  component_1_code_coding_0_display text,
  component_1_value_quantity_unit text,
  component_1_value_quantity_system text,
  component_1_value_quantity_code text,
  component_1_interpretation_0_coding_0_system text,
  component_1_interpretation_0_coding_0_code text,
  component_1_interpretation_0_coding_0_display text,
  component_2_code_coding_0_system text,
  component_2_code_coding_0_code text,
  component_2_code_coding_0_display text,
  component_2_value_quantity_unit text,
  component_2_value_quantity_system text,
  component_2_value_quantity_code text,
  reference_range_0_high_unit text,
  reference_range_0_high_code text,
  reference_range_0_high_system text,
  reference_range_0_low_unit text,
  reference_range_0_low_code text,
  reference_range_0_low_system text,
  reference_range_0_text text,
  reference_range_0_type_coding_0_system text,
  reference_range_0_type_coding_0_code text,
  reference_range_0_type_coding_0_display text,
  reference_range_0_applies_to_0_coding_0_system text,
  reference_range_0_applies_to_0_coding_0_code text,
  reference_range_0_applies_to_0_coding_0_display text,
  reference_range_0_age_low_unit text,
  reference_range_0_age_low_code text,
  reference_range_0_age_low_system text,
  reference_range_0_age_high_unit text,
  reference_range_0_age_high_code text,
  reference_range_0_age_high_system text,
  interpretation_0_coding_0_system text,
  interpretation_0_coding_0_code text,
  interpretation_0_coding_0_display text,
  interpretation_0_text text,
  data_absent_reason_coding_0_system text,
  data_absent_reason_coding_0_code text,
  data_absent_reason_coding_0_display text,
  identifier_0_system text,
  identifier_0_value text,
  identifier_0_use text,
  identifier_0_period_start timestamptz,
  identifier_0_assigner_reference text,
  note_0_text text,
  note_0_time timestamptz,
  note_0_author_reference_reference text,
  note_1_text text,
  identifier_0_assigner_display text,
  note_0_author_reference_display text,
  value_attachment_data text,
  value_attachment_hash text,
  identifier_0_period_end timestamptz,
  authored timestamptz,
  code_coding_0_version text,
  device_identifier text,
  encounter_identifier_system text,
  encounter_identifier_value text,
  meta_profile_1 text,
  meta_profile_2 text,
  meta_source text,
  note_1_time timestamptz,
  note_2_text text,
  performer_0_identifier_system text,
  performer_0_identifier_value text,
  specimen_identifier_system text,
  specimen_identifier_value text,
  subject_identifier_system text,
  subject_identifier_value text,
  value_attachment_language text,
  value_range_high_code text,
  value_range_high_system text,
  value_range_low_code text,
  value_range_low_system text,
  value_ratio_denominator_code text,
  value_ratio_denominator_system text,
  value_ratio_numerator_code text,
  value_ratio_numerator_system text,
  value_reference_display text,
  value_reference_reference text,
  value_reference_type text,
  primary key (id)
);
create index if not exists idx_observation_resource_type on fluxfhir_dev.observation (resource_type);
create index if not exists idx_observation_subject_reference on fluxfhir_dev.observation (subject_reference);
create index if not exists idx_observation_encounter_reference on fluxfhir_dev.observation (encounter_reference);
create index if not exists idx_observation_created_at on fluxfhir_dev.observation (created_at);
create index if not exists idx_observation_updated_at on fluxfhir_dev.observation (updated_at);

-- Source table Patient -> fluxfhir_dev.patient
create table if not exists fluxfhir_dev.patient (
  id text,
  resource_type text,
  active boolean,
  gender text,
  birth_date date,
  marital_status text,
  medical_record_number text,
  name_0_use text,
  name_0_family text,
  name_0_given text[],
  name_0_prefix text[],
  name_1_use text,
  name_1_family text,
  name_1_given text[],
  name_1_prefix text[],
  address_0_use text,
  address_0_type text,
  address_0_line text[],
  address_0_city text,
  address_0_district text,
  address_0_state text,
  address_0_postal_code text,
  address_0_country text,
  address_1_use text,
  address_1_type text,
  address_1_line text[],
  address_1_city text,
  address_1_district text,
  address_1_state text,
  address_1_postal_code text,
  address_1_country text,
  general_practitioner_0_reference text,
  general_practitioner_0_display text,
  general_practitioner_1_reference text,
  general_practitioner_1_display text,
  managing_organization_reference text,
  managing_organization_display text,
  race text,
  ethnicity text,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_patient_resource_type on fluxfhir_dev.patient (resource_type);
create index if not exists idx_patient_created_at on fluxfhir_dev.patient (created_at);
create index if not exists idx_patient_updated_at on fluxfhir_dev.patient (updated_at);

-- Source table Practitioner -> fluxfhir_dev.practitioner
create table if not exists fluxfhir_dev.practitioner (
  id text,
  resource_type text,
  meta_version_id text,
  meta_last_updated timestamptz,
  meta_profile_0 text,
  text_status text,
  text_div text,
  identifier_0_system text,
  identifier_0_value text,
  identifier_0_display text,
  identifier_1_system text,
  identifier_1_value text,
  identifier_1_display text,
  identifier_2_system text,
  identifier_2_value text,
  identifier_2_display text,
  active boolean,
  name_0_use text,
  name_0_family text,
  name_0_given_0 text,
  name_0_prefix_0 text,
  name_1_use text,
  name_1_family text,
  name_1_given_0 text,
  name_1_given_1 text,
  telecom_0_system text,
  telecom_0_value text,
  telecom_0_use text,
  telecom_1_system text,
  telecom_1_value text,
  telecom_1_use text,
  telecom_2_system text,
  telecom_2_value text,
  telecom_2_use text,
  address_0_use text,
  address_0_type text,
  address_0_text text,
  address_0_line_0 text,
  address_0_line_1 text,
  address_0_city text,
  address_0_state text,
  address_0_postal_code text,
  address_0_country text,
  gender text,
  birth_date date,
  qualification_0_identifier_0_system text,
  qualification_0_identifier_0_value text,
  qualification_0_code_coding_0_system text,
  qualification_0_code_coding_0_code text,
  qualification_0_code_coding_0_display text,
  qualification_0_code_text text,
  qualification_0_period_start date,
  qualification_0_period_end date,
  qualification_0_issuer_display text,
  qualification_1_code_coding_0_system text,
  qualification_1_code_coding_0_code text,
  qualification_1_code_coding_0_display text,
  qualification_1_code_text text,
  qualification_1_period_start date,
  qualification_1_period_end date,
  qualification_1_issuer_display text,
  communication_0_language_coding_0_system text,
  communication_0_language_coding_0_code text,
  communication_0_language_coding_0_display text,
  communication_0_preferred boolean,
  communication_1_language_coding_0_system text,
  communication_1_language_coding_0_code text,
  communication_1_language_coding_0_display text,
  communication_1_preferred boolean,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_practitioner_resource_type on fluxfhir_dev.practitioner (resource_type);
create index if not exists idx_practitioner_created_at on fluxfhir_dev.practitioner (created_at);
create index if not exists idx_practitioner_updated_at on fluxfhir_dev.practitioner (updated_at);

-- Source table Procedure -> fluxfhir_dev.procedure
create table if not exists fluxfhir_dev.procedure (
  id text,
  resource_type text,
  status text,
  category_0_coding_0_system text,
  category_0_coding_0_code text,
  category_0_coding_0_display text,
  category_0_text text,
  code_coding_0_system text,
  code_coding_0_code text,
  code_coding_0_display text,
  code_coding_1_system text,
  code_coding_1_code text,
  code_coding_1_display text,
  code_text text,
  subject_reference text,
  subject_display text,
  encounter_reference text,
  encounter_display text,
  occurrence_period_start timestamptz,
  occurrence_period_end timestamptz,
  occurrence_date_time timestamptz,
  recorded timestamptz,
  recorder_reference text,
  recorder_display text,
  performer_0_actor_reference text,
  performer_0_actor_display text,
  performer_0_function_coding_0_system text,
  performer_0_function_coding_0_code text,
  performer_0_function_coding_0_display text,
  performer_1_actor_reference text,
  performer_1_actor_display text,
  performer_1_function_coding_0_system text,
  performer_1_function_coding_0_code text,
  performer_1_function_coding_0_display text,
  location_reference text,
  location_display text,
  reason_0_concept_coding_0_system text,
  reason_0_concept_coding_0_code text,
  reason_0_concept_coding_0_display text,
  reason_0_concept_text text,
  reason_0_reference_reference text,
  reason_0_reference_display text,
  body_site_0_coding_0_system text,
  body_site_0_coding_0_code text,
  body_site_0_coding_0_display text,
  body_site_0_coding_1_system text,
  body_site_0_coding_1_code text,
  body_site_0_coding_1_display text,
  body_site_0_text text,
  used_code_0_concept_coding_0_system text,
  used_code_0_concept_coding_0_code text,
  used_code_0_concept_coding_0_display text,
  used_code_0_concept_text text,
  report_0_reference text,
  report_0_display text,
  status_reason_coding_0_system text,
  status_reason_coding_0_code text,
  status_reason_coding_0_display text,
  outcome_coding_0_system text,
  outcome_coding_0_code text,
  outcome_coding_0_display text,
  outcome_text text,
  note_0_text text,
  note_0_time timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_procedure_resource_type on fluxfhir_dev.procedure (resource_type);
create index if not exists idx_procedure_subject_reference on fluxfhir_dev.procedure (subject_reference);
create index if not exists idx_procedure_encounter_reference on fluxfhir_dev.procedure (encounter_reference);
create index if not exists idx_procedure_created_at on fluxfhir_dev.procedure (created_at);
create index if not exists idx_procedure_updated_at on fluxfhir_dev.procedure (updated_at);

-- Source table Task -> fluxfhir_dev.task
create table if not exists fluxfhir_dev.task (
  id text,
  resource_type text,
  meta_version_id text,
  meta_last_updated timestamptz,
  meta_source text,
  meta_profile_0 text,
  meta_security_0_system text,
  meta_security_0_code text,
  meta_security_0_display text,
  meta_tag_0_system text,
  meta_tag_0_code text,
  meta_tag_0_display text,
  text_status text,
  text_div text,
  identifier_0_use text,
  identifier_0_type_coding_0_system text,
  identifier_0_type_coding_0_code text,
  identifier_0_type_coding_0_display text,
  identifier_0_system text,
  identifier_0_value text,
  identifier_0_period_start timestamptz,
  identifier_0_period_end timestamptz,
  identifier_0_assigner_display text,
  status text,
  status_reason_coding_0_system text,
  status_reason_coding_0_code text,
  status_reason_coding_0_display text,
  status_reason_text text,
  business_status_coding_0_system text,
  business_status_coding_0_code text,
  business_status_coding_0_display text,
  business_status_text text,
  intent text,
  priority text,
  code_coding_0_system text,
  code_coding_0_code text,
  code_coding_0_display text,
  code_text text,
  description text,
  focus_reference text,
  focus_display text,
  focus_type_coding_0_system text,
  focus_type_coding_0_code text,
  based_on_0_reference text,
  based_on_0_display text,
  dependency_0_reference text,
  dependency_0_display text,
  for_reference text,
  for_display text,
  encounter_reference text,
  encounter_display text,
  authored_on timestamptz,
  last_modified timestamptz,
  requester_reference text,
  requester_display text,
  requester_on_behalf_of_reference text,
  requester_on_behalf_of_display text,
  owner_reference text,
  owner_display text,
  reason_code_0_coding_0_system text,
  reason_code_0_coding_0_code text,
  reason_code_0_coding_0_display text,
  reason_code_0_text text,
  reason_reference_0_reference text,
  reason_reference_0_display text,
  execution_period_start timestamptz,
  execution_period_end timestamptz,
  scheduled_timing_event_0 timestamptz,
  scheduled_timing_repeat_bounds_duration_unit text,
  scheduled_timing_repeat_bounds_duration_system text,
  scheduled_timing_repeat_bounds_duration_code text,
  scheduled_timing_repeat_period_unit text,
  input_0_type_coding_0_system text,
  input_0_type_coding_0_code text,
  input_0_value_reference_reference text,
  input_0_value_reference_display text,
  input_0_value_codeable_concept_coding_0_system text,
  input_0_value_codeable_concept_coding_0_code text,
  output_0_type_coding_0_system text,
  output_0_type_coding_0_code text,
  output_0_value_reference_reference text,
  output_0_value_reference_display text,
  note_0_author_reference_reference text,
  note_0_author_reference_display text,
  note_0_time timestamptz,
  note_0_text text,
  relevant_history_0_reference text,
  relevant_history_0_display text,
  created_at timestamptz,
  updated_at timestamptz,
  is_deleted boolean,
  primary key (id)
);
create index if not exists idx_task_resource_type on fluxfhir_dev.task (resource_type);
create index if not exists idx_task_encounter_reference on fluxfhir_dev.task (encounter_reference);
create index if not exists idx_task_created_at on fluxfhir_dev.task (created_at);
create index if not exists idx_task_updated_at on fluxfhir_dev.task (updated_at);

